name: "NPM Cloudflare Sync"
version: "1.0.0"
slug: "npm_cloudflare_sync"
description: "Sync Nginx Proxy Manager hosts with Cloudflare DNS"
url: "https://github.com/rvbcrs/npm-cloudflare-sync"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
options:
  CF_API_TOKEN: ""
  CF_EMAIL: ""
  NPM_API_URL: "http://npm:81"
  NPM_EMAIL: ""
  NPM_PASSWORD: ""
  CHECK_INTERVAL: 10000
  LOG_LEVEL: "info"
  AUTO_CREATE_ROOT_RECORDS: false
schema:
  CF_API_TOKEN: str
  CF_EMAIL: str
  NPM_API_URL: str
  NPM_EMAIL: str
  NPM_PASSWORD: str
  CHECK_INTERVAL: int
  LOG_LEVEL: list(info, debug, warn, error)
  AUTO_CREATE_ROOT_RECORDS: bool
